export const categories: Category[] = [
  {
    id: 400,
    parent_id: 2,
    name: "Women",
    is_active: true,
    position: 1,
    level: 2,
    product_count: 304,
    children_data: [
      {
        id: 448,
        parent_id: 400,
        name: "Makeup",
        is_active: true,
        position: 1,
        level: 3,
        product_count: 153,
        children_data: [
          {
            id: 451,
            parent_id: 448,
            name: "Face",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 39,
            children_data: [],
          },
          {
            id: 457,
            parent_id: 448,
            name: "Lips",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 27,
            children_data: [],
          },
          {
            id: 455,
            parent_id: 448,
            name: "Eyes",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 13,
            children_data: [],
          },
          {
            id: 452,
            parent_id: 448,
            name: "Brows",
            is_active: true,
            position: 4,
            level: 4,
            product_count: 14,
            children_data: [],
          },
          {
            id: 456,
            parent_id: 448,
            name: "Lashes",
            is_active: true,
            position: 5,
            level: 4,
            product_count: 10,
            children_data: [],
          },
          {
            id: 454,
            parent_id: 448,
            name: "Lenses",
            is_active: true,
            position: 6,
            level: 4,
            product_count: 47,
            children_data: [],
          },
          {
            id: 449,
            parent_id: 448,
            name: "Makeup Removers",
            is_active: true,
            position: 7,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 453,
            parent_id: 448,
            name: "Makeup Tools",
            is_active: true,
            position: 7,
            level: 4,
            product_count: 2,
            children_data: [],
          },
          {
            id: 450,
            parent_id: 448,
            name: "Makeup Sets",
            is_active: true,
            position: 7,
            level: 4,
            product_count: 2,
            children_data: [],
          },
        ],
      },
      {
        id: 470,
        parent_id: 400,
        name: "Skincare",
        is_active: true,
        position: 2,
        level: 3,
        product_count: 19,
        children_data: [
          {
            id: 475,
            parent_id: 470,
            name: "Lips",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 476,
            parent_id: 470,
            name: "Neck & Decolte",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 474,
            parent_id: 470,
            name: "Facial Tools",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 473,
            parent_id: 470,
            name: "Face",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 14,
            children_data: [],
          },
          {
            id: 472,
            parent_id: 470,
            name: "Eyes",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 3,
            children_data: [],
          },
          {
            id: 471,
            parent_id: 470,
            name: "Skin Care Sets",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 406,
        parent_id: 400,
        name: "Bodycare",
        is_active: true,
        position: 3,
        level: 3,
        product_count: 1,
        children_data: [
          {
            id: 411,
            parent_id: 406,
            name: "Personal Higene",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 412,
            parent_id: 406,
            name: "Feet",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 413,
            parent_id: 406,
            name: "Hands",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 414,
            parent_id: 406,
            name: "Intimate",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 410,
            parent_id: 406,
            name: "Massage",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 409,
            parent_id: 406,
            name: "Bath & Shower",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 408,
            parent_id: 406,
            name: "Body Treatments",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 407,
            parent_id: 406,
            name: "Tanning",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 427,
        parent_id: 400,
        name: "Haircare",
        is_active: true,
        position: 4,
        level: 3,
        product_count: 45,
        children_data: [
          {
            id: 428,
            parent_id: 427,
            name: "Hair Tools",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 429,
            parent_id: 427,
            name: "Hair Treatments",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 29,
            children_data: [],
          },
          {
            id: 430,
            parent_id: 427,
            name: "Hair Styling",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 10,
            children_data: [],
          },
          {
            id: 431,
            parent_id: 427,
            name: "Hair Color",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 5,
            children_data: [],
          },
          {
            id: 919,
            parent_id: 427,
            name: "Hair Care Sets",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 1,
            children_data: [],
          },
        ],
      },
      {
        id: 458,
        parent_id: 400,
        name: "Nails",
        is_active: true,
        position: 5,
        level: 3,
        product_count: 11,
        children_data: [
          {
            id: 460,
            parent_id: 458,
            name: "Nail Treatments",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 461,
            parent_id: 458,
            name: "Nail Tools",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 868,
            parent_id: 458,
            name: "Nail Polish",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 10,
            children_data: [],
          },
        ],
      },
      {
        id: 401,
        parent_id: 400,
        name: "Accessories",
        is_active: true,
        position: 6,
        level: 3,
        product_count: 19,
        children_data: [
          {
            id: 873,
            parent_id: 401,
            name: "Head Accessories",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 9,
            children_data: [],
          },
          {
            id: 874,
            parent_id: 401,
            name: "Neck Accessories",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 5,
            children_data: [],
          },
          {
            id: 875,
            parent_id: 401,
            name: "Hand Accessories",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 4,
            children_data: [],
          },
          {
            id: 876,
            parent_id: 401,
            name: "Nails",
            is_active: true,
            position: 4,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 877,
            parent_id: 401,
            name: "Leather Goods",
            is_active: true,
            position: 5,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 878,
        parent_id: 400,
        name: "Fragrances",
        is_active: true,
        position: 7,
        level: 3,
        product_count: 56,
        children_data: [
          {
            id: 883,
            parent_id: 878,
            name: "Designer Fragrances",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 4,
            children_data: [],
          },
          {
            id: 884,
            parent_id: 878,
            name: "International Fragrances",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 22,
            children_data: [],
          },
          {
            id: 885,
            parent_id: 878,
            name: "Niche Fragrances",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 30,
            children_data: [],
          },
        ],
      },
    ],
  },
  {
    id: 310,
    parent_id: 2,
    name: "Men",
    is_active: true,
    position: 2,
    level: 2,
    product_count: 81,
    children_data: [
      {
        id: 361,
        parent_id: 310,
        name: "Skincare",
        is_active: true,
        position: 1,
        level: 3,
        product_count: 10,
        children_data: [
          {
            id: 362,
            parent_id: 361,
            name: "Skincare Sets",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 363,
            parent_id: 361,
            name: "Eyes",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 364,
            parent_id: 361,
            name: "Face",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 8,
            children_data: [],
          },
          {
            id: 365,
            parent_id: 361,
            name: "Facial Tools",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 366,
            parent_id: 361,
            name: "Lips",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 367,
            parent_id: 361,
            name: "Sun Screens",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 316,
        parent_id: 310,
        name: "Bodycare",
        is_active: true,
        position: 2,
        level: 3,
        product_count: 0,
        children_data: [
          {
            id: 318,
            parent_id: 316,
            name: "Deodorants",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 319,
            parent_id: 316,
            name: "Tanning",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 320,
            parent_id: 316,
            name: "Body Treatments",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 321,
            parent_id: 316,
            name: "Bath & Shower",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 322,
            parent_id: 316,
            name: "Massage",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 323,
            parent_id: 316,
            name: "Personal Higene",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 324,
            parent_id: 316,
            name: "Feet",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 325,
            parent_id: 316,
            name: "Hands",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 335,
        parent_id: 310,
        name: "Haircare",
        is_active: true,
        position: 3,
        level: 3,
        product_count: 1,
        children_data: [
          {
            id: 336,
            parent_id: 335,
            name: "Beardcare",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 337,
            parent_id: 335,
            name: "Hair Tools",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 338,
            parent_id: 335,
            name: "Hair Treatments",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 339,
            parent_id: 335,
            name: "Hair Color",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 340,
            parent_id: 335,
            name: "Hair Styling",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 341,
            parent_id: 335,
            name: "Shaving",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 879,
        parent_id: 310,
        name: "Fragrances",
        is_active: true,
        position: 3,
        level: 3,
        product_count: 57,
        children_data: [
          {
            id: 880,
            parent_id: 879,
            name: "International Fragrances",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 18,
            children_data: [],
          },
          {
            id: 881,
            parent_id: 879,
            name: "Designer Fragrances",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 7,
            children_data: [],
          },
          {
            id: 882,
            parent_id: 879,
            name: "Niche Fragrances",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 32,
            children_data: [],
          },
        ],
      },
      {
        id: 311,
        parent_id: 310,
        name: "Accessories",
        is_active: true,
        position: 4,
        level: 3,
        product_count: 13,
        children_data: [
          {
            id: 869,
            parent_id: 311,
            name: "Head Accessories",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 5,
            children_data: [],
          },
          {
            id: 870,
            parent_id: 311,
            name: "Neck Accessories",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 4,
            children_data: [],
          },
          {
            id: 871,
            parent_id: 311,
            name: "Hand Accessories",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 4,
            children_data: [],
          },
          {
            id: 872,
            parent_id: 311,
            name: "Leather Goods",
            is_active: true,
            position: 4,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
    ],
  },
  {
    id: 200,
    parent_id: 2,
    name: "Baby",
    is_active: true,
    position: 3,
    level: 2,
    product_count: 1,
    children_data: [
      {
        id: 201,
        parent_id: 200,
        name: "Baby Essentials",
        is_active: true,
        position: 1,
        level: 3,
        product_count: 0,
        children_data: [
          {
            id: 218,
            parent_id: 201,
            name: "Teats",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 219,
            parent_id: 201,
            name: "Teethers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 220,
            parent_id: 201,
            name: "Thermometers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 221,
            parent_id: 201,
            name: "Toilet Trainers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 222,
            parent_id: 201,
            name: "Toilet Training Seats",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 223,
            parent_id: 201,
            name: "Baby Gas Passer",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 217,
            parent_id: 201,
            name: "Snot Suckers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 216,
            parent_id: 201,
            name: "Snot Sprays",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 215,
            parent_id: 201,
            name: "Potty Training Tabs",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 202,
            parent_id: 201,
            name: "Baby Bags",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 203,
            parent_id: 201,
            name: "Baby Baskets",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 204,
            parent_id: 201,
            name: "Baby Nail Clippers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 205,
            parent_id: 201,
            name: "Baby Nail Scissors",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 206,
            parent_id: 201,
            name: "Bouncing Cradles",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 207,
            parent_id: 201,
            name: "Changing Mats",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 208,
            parent_id: 201,
            name: "Changing Pads",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 209,
            parent_id: 201,
            name: "Diapers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 210,
            parent_id: 201,
            name: "Drying Racks",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 211,
            parent_id: 201,
            name: "Mats",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 212,
            parent_id: 201,
            name: "Pacifier Clips",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 213,
            parent_id: 201,
            name: "Pacifiers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 214,
            parent_id: 201,
            name: "Potty Chairs",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 258,
            parent_id: 201,
            name: "Baby Potties",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 261,
            parent_id: 201,
            name: "Baby Towels",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 232,
        parent_id: 200,
        name: "Baby Feeding",
        is_active: true,
        position: 2,
        level: 3,
        product_count: 0,
        children_data: [
          {
            id: 280,
            parent_id: 232,
            name: "Bowls",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 281,
            parent_id: 232,
            name: "Cooling Bags",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 233,
            parent_id: 232,
            name: "Baby Bottles",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 234,
            parent_id: 232,
            name: "Cups",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 235,
            parent_id: 232,
            name: "Cuttlery",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 236,
            parent_id: 232,
            name: "Food Containers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 237,
            parent_id: 232,
            name: "Formula Containers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 238,
            parent_id: 232,
            name: "Ice Packs",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 239,
            parent_id: 232,
            name: "Plates",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 240,
            parent_id: 232,
            name: "Squeeze Bags",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 241,
            parent_id: 232,
            name: "Straw Cups",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 242,
            parent_id: 232,
            name: "Thermos Bottles",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 262,
            parent_id: 232,
            name: "Bibs",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 259,
        parent_id: 200,
        name: "Baby Skincare",
        is_active: true,
        position: 3,
        level: 3,
        product_count: 0,
        children_data: [
          {
            id: 273,
            parent_id: 259,
            name: "Skin Cleansers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 274,
            parent_id: 259,
            name: "Skin Protective Creams",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 275,
            parent_id: 259,
            name: "Skin Protective Lotions",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 276,
            parent_id: 259,
            name: "Skin Repair Creams",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 277,
            parent_id: 259,
            name: "Skin Soothing Balms",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 278,
            parent_id: 259,
            name: "Skin Soothing Creams",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 279,
            parent_id: 259,
            name: "Thermal Water",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 269,
            parent_id: 259,
            name: "Cradle Cap Cream",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 268,
            parent_id: 259,
            name: "Body Washes",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 267,
            parent_id: 259,
            name: "Body Sprays",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 266,
            parent_id: 259,
            name: "Body Oils",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 264,
            parent_id: 259,
            name: "Body Moisturizing Milks",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 260,
            parent_id: 259,
            name: "Baby Sunscreen Lotions",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 263,
            parent_id: 259,
            name: "Baby Wipes",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 270,
            parent_id: 259,
            name: "Hand Washes",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 265,
            parent_id: 259,
            name: "Body Nourishing Creams",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 272,
            parent_id: 259,
            name: "Skin Brushes",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 271,
            parent_id: 259,
            name: "Nappy Rash Creams",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 283,
        parent_id: 200,
        name: "Gifts & Toys",
        is_active: true,
        position: 4,
        level: 3,
        product_count: 0,
        children_data: [
          {
            id: 284,
            parent_id: 283,
            name: "Comfort Blankets",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 285,
            parent_id: 283,
            name: "Baby Print",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 286,
            parent_id: 283,
            name: "Baby Record Books",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 287,
            parent_id: 283,
            name: "Baby Toys",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 288,
            parent_id: 283,
            name: "Boxes",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 289,
            parent_id: 283,
            name: "Play Mats",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 290,
            parent_id: 283,
            name: "Rotating Toys",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 291,
            parent_id: 283,
            name: "Soft Toys",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 282,
        parent_id: 200,
        name: "Baby Value Packs",
        is_active: true,
        position: 4,
        level: 3,
        product_count: 0,
        children_data: [],
      },
      {
        id: 254,
        parent_id: 200,
        name: "Baby Haircare",
        is_active: true,
        position: 4,
        level: 3,
        product_count: 0,
        children_data: [
          {
            id: 255,
            parent_id: 254,
            name: "Hair Accessories",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 256,
            parent_id: 254,
            name: "Hair Tools",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 224,
        parent_id: 200,
        name: "Baby Bath",
        is_active: true,
        position: 4,
        level: 3,
        product_count: 1,
        children_data: [
          {
            id: 246,
            parent_id: 224,
            name: "Baby Furniture",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [
              {
                id: 250,
                parent_id: 246,
                name: "Bouncers",
                is_active: true,
                position: 1,
                level: 5,
                product_count: 0,
                children_data: [],
              },
              {
                id: 252,
                parent_id: 246,
                name: "Photo Frames",
                is_active: true,
                position: 1,
                level: 5,
                product_count: 0,
                children_data: [],
              },
              {
                id: 253,
                parent_id: 246,
                name: "Step Stools",
                is_active: true,
                position: 1,
                level: 5,
                product_count: 0,
                children_data: [],
              },
              {
                id: 257,
                parent_id: 246,
                name: "Baby Night Lights",
                is_active: true,
                position: 1,
                level: 5,
                product_count: 0,
                children_data: [],
              },
              {
                id: 248,
                parent_id: 246,
                name: "Baby Rockers",
                is_active: true,
                position: 1,
                level: 5,
                product_count: 0,
                children_data: [],
              },
              {
                id: 249,
                parent_id: 246,
                name: "Baby Sway Chairs",
                is_active: true,
                position: 1,
                level: 5,
                product_count: 0,
                children_data: [],
              },
              {
                id: 251,
                parent_id: 246,
                name: "Cribs",
                is_active: true,
                position: 1,
                level: 5,
                product_count: 0,
                children_data: [],
              },
              {
                id: 247,
                parent_id: 246,
                name: "Baby Docking Station",
                is_active: true,
                position: 1,
                level: 5,
                product_count: 0,
                children_data: [],
              },
            ],
          },
          {
            id: 225,
            parent_id: 224,
            name: "Baby Bath Stands",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 226,
            parent_id: 224,
            name: "Baby Bath Tubs",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 227,
            parent_id: 224,
            name: "Shampoos & Conditioners",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 228,
            parent_id: 224,
            name: "Shower Gels",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 229,
            parent_id: 224,
            name: "Baby Bath Seats",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 230,
            parent_id: 224,
            name: "Bath Toys",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 231,
            parent_id: 224,
            name: "Drain Covers",
            is_active: true,
            position: 2,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 243,
        parent_id: 200,
        name: "Baby Fragrances",
        is_active: true,
        position: 4,
        level: 3,
        product_count: 0,
        children_data: [
          {
            id: 245,
            parent_id: 243,
            name: "Eau De Toilette",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 244,
            parent_id: 243,
            name: "Perfume Gift Sets",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
    ],
  },
  {
    id: 292,
    parent_id: 2,
    name: "Home",
    is_active: true,
    position: 4,
    level: 2,
    product_count: 3,
    children_data: [
      {
        id: 297,
        parent_id: 292,
        name: "Home Fragrances",
        is_active: true,
        position: 1,
        level: 3,
        product_count: 2,
        children_data: [
          {
            id: 298,
            parent_id: 297,
            name: "Candles",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 299,
            parent_id: 297,
            name: "Diffusers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 300,
            parent_id: 297,
            name: "Essential Oils",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 301,
            parent_id: 297,
            name: "Fabric Sprays",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 302,
            parent_id: 297,
            name: "Gift Sets",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 303,
            parent_id: 297,
            name: "Home Sprays",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 304,
            parent_id: 297,
            name: "Incense",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 305,
            parent_id: 297,
            name: "Oil Burners",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 306,
            parent_id: 297,
            name: "Incense Burners",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
      {
        id: 293,
        parent_id: 292,
        name: "Home Accessories",
        is_active: true,
        position: 1,
        level: 3,
        product_count: 1,
        children_data: [
          {
            id: 295,
            parent_id: 293,
            name: "Décor",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            children_data: [],
          },
          {
            id: 296,
            parent_id: 293,
            name: "Gift Sets",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
          {
            id: 294,
            parent_id: 293,
            name: "Air Purifiers",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            children_data: [],
          },
        ],
      },
    ],
  },
  {
    id: 886,
    parent_id: 2,
    name: "Top Rated",
    is_active: true,
    position: 5,
    level: 2,
    product_count: 115,
    children_data: [],
  },
  {
    id: 866,
    parent_id: 2,
    name: "Gift Cards",
    is_active: true,
    position: 5,
    level: 2,
    product_count: 28,
    children_data: [],
  },
  {
    id: 920,
    parent_id: 2,
    name: "Shop All",
    is_active: true,
    position: 5,
    level: 2,
    product_count: 343,
    children_data: [],
  },
];
